CREATE TABLE Sales
(
編號 CHAR(5),
品號 CHAR(5),
數量 INT NOT NULL,
PRIMARY KEY(編號,品號),
FOREIGN KEY(編號) REFERENCES Employee(Em_id)
ON UPDATE CASCADE
ON DELETE CASCADE,
FOREIGN KEY(品號) REFERENCES Product(P_id)
)